import jsPDF from "jspdf";
import { ValidationReport } from "../types";

export const generatePDF = (report: ValidationReport, ideaText: string) => {
    const doc = new jsPDF();
    const pageWidth = doc.internal.pageSize.getWidth();
    const margin = 20;
    let y = 20;

    // Helper for centered text
    const centerText = (text: string, yPos: number, size = 12) => {
        doc.setFontSize(size);
        const textWidth = doc.getTextWidth(text);
        doc.text(text, (pageWidth - textWidth) / 2, yPos);
    };

    // Helper for wrapping text
    const addWrappedText = (text: string, yPos: number, fontSize = 10, fontStyle = "normal", color = [0, 0, 0]) => {
        doc.setFontSize(fontSize);
        doc.setFont("helvetica", fontStyle);
        doc.setTextColor(color[0], color[1], color[2]);
        const lines = doc.splitTextToSize(text, pageWidth - margin * 2);
        doc.text(lines, margin, yPos);
        return lines.length * (fontSize * 0.5) + 5; // Return approximate height used
    };

    // --- HEADER ---
    doc.setFillColor(0, 0, 0); // Black header
    doc.rect(0, 0, pageWidth, 40, "F");

    doc.setTextColor(255, 255, 255);
    doc.setFont("helvetica", "bold");
    centerText("IDEA VALIDATOR // INTELLIGENCE REPORT", 25, 16);

    doc.setFont("helvetica", "normal");
    doc.setFontSize(10);
    doc.setTextColor(200, 200, 200);
    doc.text(`DATE: ${new Date().toLocaleDateString().toUpperCase()}`, margin, 35);
    doc.text("CONFIDENTIALITY: STRICT", pageWidth - margin - 50, 35);

    y = 55;

    // --- VERDICT SECTION ---
    doc.setTextColor(0, 0, 0);
    doc.setFont("helvetica", "bold");
    doc.setFontSize(10);
    doc.text("FINAL VERDICT:", margin, y);

    // Color code verdict
    const verdictColor = report.verdict === "Build Now" ? [0, 150, 0] :
        report.verdict === "Build with Caution" ? [200, 150, 0] : [200, 0, 0];

    doc.setTextColor(verdictColor[0], verdictColor[1], verdictColor[2]);
    doc.setFontSize(24);
    doc.text(report.verdict.toUpperCase(), margin, y + 10);

    y += 25;

    // --- SCORES GRID (Simple text representation) ---
    doc.setDrawColor(200, 200, 200);
    doc.line(margin, y, pageWidth - margin, y);
    y += 10;

    doc.setTextColor(0, 0, 0);
    doc.setFontSize(10);
    doc.setFont("helvetica", "bold");

    doc.text(`PROBLEM SCORE: ${report.problemSeverity}/10`, margin, y);
    doc.text(`MARKET DEMAND: ${report.marketDemand.toUpperCase()}`, margin + 60, y);
    doc.text(`CONFIDENCE: ${report.confidenceScore.toUpperCase()}`, margin + 120, y);

    y += 15;
    doc.line(margin, y - 5, pageWidth - margin, y - 5);

    // --- IDEA SUMMARY ---
    y += 10;
    doc.setFont("helvetica", "bold");
    doc.text("IDEA SUMMARY", margin, y);
    y += 7;
    y += addWrappedText(report.summary, y, 10, "normal");

    // --- WHY IT FAILS (Critical) ---
    y += 10;
    doc.setTextColor(200, 0, 0);
    doc.setFont("helvetica", "bold");
    doc.text("CRITICAL RISK FACTORS (WHY IT FAILS)", margin, y);
    y += 7;
    y += addWrappedText(report.whyItFails, y, 10, "normal", [50, 0, 0]);

    // --- MVP SCOPE ---
    y += 10;
    doc.setTextColor(0, 0, 50);
    doc.setFont("helvetica", "bold");
    doc.text("RECOMMENDED MVP SCOPE", margin, y);
    y += 7;
    y += addWrappedText(report.mvpScope, y, 10, "normal", [0, 0, 0]);

    // --- MONETIZATION ---
    y += 10;
    doc.setFont("helvetica", "bold");
    doc.text("MONETIZATION STRATEGY", margin, y);
    y += 7;
    const metrics = report.monetizationPaths.join(" | ");
    y += addWrappedText(metrics, y, 10, "italic", [0, 0, 0]);

    // --- COMPETITORS ---
    y += 10;
    doc.setFont("helvetica", "bold");
    doc.text("KNOWN COMPETITORS", margin, y);
    y += 7;
    const comps = report.alternatives.join(", ");
    y += addWrappedText(comps, y, 10, "normal", [0, 0, 0]);

    // --- FOOTER ---
    const pageHeight = doc.internal.pageSize.getHeight();
    doc.setFillColor(240, 240, 240);
    doc.rect(0, pageHeight - 20, pageWidth, 20, "F");
    doc.setFontSize(8);
    doc.setTextColor(100, 100, 100);
    centerText("GENERATED BY IDEA VALIDATOR", pageHeight - 8);

    doc.save("IdeaValidator_Report.pdf");
};
